### ISSUE TITLE
Arrays of structs

### ISSUE THREAD

**Issue by apla** [TooTallNate/ref-array#5]
Hi!

I trying to build interface to the `libclang.codeCompleteAt`. So far so good, but I have an issue with `ref-array` when using array of structs.

When I pass struct as array type, then I get assertion failed at [this line](https://github.com/TooTallNate/ref-array/blob/master/lib/array.js#L81). Commenting out this line fixes issue for me. `expectedLength` must match pointer size for my case.

Struct description:
``` javascript
var CXCompletionResult = exports.CXCompletionResult = Struct({
	CursorKind: ref.types.uint32,
	CompletionString: CXCompletionString,
});
var CXCompletionResultPtr = exports.CXCompletionResultPtr = ref.refType(CXCompletionResult);
var CXCodeCompleteResults = exports.CXCodeCompleteResults = Struct({
	Results: CXCompletionResultPtr,
	NumResults: ref.types.uint32,
});
```

FFI call code:
```javascript
	var codeCompletionOptions = lib.clang_defaultCodeCompleteOptions ();

	var completionResultsRef = lib.clang_codeCompleteAt (
		this._instance,
		fileName,
		lineNo,
		columnNo,
		null, 0, codeCompletionOptions
	);

	var completionResults = completionResultsRef.deref();
	console.log ('completion result count: ', completionResults.NumResults);

	var results = completionResults.Results;
	if (completionResults.NumResults > 0) {

		if (!('CompletionString' in results.type.fields)) {
			console.log ('wrong data, no CompletionString in type definition');
		}

		var CompletionArray = ArrayType (d.CXCompletionResult);
		var completions = new CompletionArray (completionResults.Results, completionResults.NumResults);
		...
	}
```

**Comment by robgrimball** [comment]
Just a quick comment to this, though it has been a while since I worked with this problem.

The following link is probably related to what you are encountering.  Nate said he fixed it in ref-struct, but before he did, I had converted to just using a linked list instead of an array of structs, so I never got around to testing out the fix.  If you are so inclined, you may want to check out the link and comment on your experience.

https://github.com/TooTallNate/ref-struct/issues/11
